import Link from "next/link";
import type { ReactNode } from "react";

const NAV: { href: string; label: string; key: string }[] = [
  { href: "/", label: "Fleet", key: "fleet" },
  { href: "/replay", label: "Failure replay", key: "replay" },
  { href: "/agent", label: "Ask the agent", key: "agent" },
];

export default function AppShell({
  active,
  children,
}: {
  active: string;
  children: ReactNode;
}) {
  return (
    <div className="mx-auto flex w-full max-w-7xl flex-col px-4 py-6 sm:px-6 lg:px-8">
      <header className="flex flex-wrap items-center justify-between gap-4 border-b border-line pb-4">
        <div className="flex items-center gap-3">
          <span
            aria-hidden
            className="grid h-10 w-10 place-items-center rounded-lg bg-teal text-lg font-semibold text-white"
          >
            PM
          </span>
          <div>
            <div className="text-sm font-semibold uppercase tracking-wide text-ink">
              Mysuru Manufacturing
            </div>
            <div className="text-xs text-ink/55">
              Predictive maintenance · control room
            </div>
          </div>
        </div>

        <nav aria-label="Screens" className="order-3 flex flex-wrap gap-1 sm:order-2">
          {NAV.map((item) => {
            const on = item.key === active;
            return (
              <Link
                key={item.key}
                href={item.href}
                aria-current={on ? "page" : undefined}
                className={
                  "inline-flex min-h-11 items-center rounded-md px-3 text-sm font-medium transition-colors " +
                  (on
                    ? "bg-teal/10 text-teal"
                    : "text-ink/70 hover:bg-ink/5 hover:text-ink")
                }
              >
                {item.label}
              </Link>
            );
          })}
        </nav>

        <span className="order-2 inline-flex min-h-9 items-center gap-2 rounded-full border border-teal/30 bg-teal/10 px-3 text-xs font-medium text-teal sm:order-3">
          <span className="h-2 w-2 animate-pulse rounded-full bg-teal" />
          Simulated live{isMockLabel()}
        </span>
      </header>

      <main className="mt-6">{children}</main>

      <footer className="mt-10 border-t border-line pt-4 text-xs text-ink/55">
        All data is simulated and generated by our own physics-grounded
        simulator. Subsystem attributions are suspected, not confirmed faults.
        Lead-time numbers demonstrate the method, not field accuracy.
      </footer>
    </div>
  );
}

function isMockLabel(): string {
  // NEXT_PUBLIC_USE_MOCK !== "false" is the default, so the badge usually reads MOCK.
  return process.env.NEXT_PUBLIC_USE_MOCK === "false" ? "" : " · MOCK";
}
